# Generated by Django 3.0.5 on 2020-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configblog',
            name='footerTitle',
            field=models.CharField(max_length=50),
        ),
    ]
