# Generated by Django 3.0.5 on 2020-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigBlog', '0002_auto_20200818_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='configblog',
            name='abouts',
            field=models.ManyToManyField(blank=True, related_name='aboutField', to='ConfigBlog.aboutFields'),
        ),
    ]
