# Generated by Django 3.0.5 on 2020-09-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigBlog', '0003_auto_20200910_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfields',
            name='conf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ConfigBlog.ConfigBlog'),
        ),
        migrations.AlterField(
            model_name='configblog',
            name='abouts',
            field=models.ManyToManyField(to='ConfigBlog.AboutFields'),
        ),
    ]
