# Generated by Django 3.0.5 on 2020-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigBlog', '0004_auto_20200910_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfields',
            name='icon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='configblog',
            name='abouts',
            field=models.ManyToManyField(to='ConfigBlog.AboutFields'),
        ),
    ]
