# Generated by Django 3.0.5 on 2020-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigBlog', '0006_auto_20200911_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configblog',
            name='abouts',
            field=models.ManyToManyField(to='ConfigBlog.AboutFields'),
        ),
    ]
