# Generated by Django 3.0.5 on 2020-07-31 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('shortDescription', models.TextField(default='Add a short description about you.', max_length=50)),
                ('aboutMe', models.CharField(default='Write something about you.', max_length=500)),
                ('profileImage', models.ImageField(blank=True, default='default.jpg', upload_to='profileImages')),
                ('favoritePosts', models.ManyToManyField(blank=True, related_name='favoritePosts', to='blog.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
