# Generated by Django 3.0.5 on 2020-09-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='profileImages/default.jpg', upload_to='profileImages'),
        ),
    ]
