# Generated by Django 3.0.5 on 2020-07-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('url', models.URLField(max_length=150)),
                ('logo', models.ImageField(upload_to='SocialMediaLogo')),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
