# Generated by Django 3.0.5 on 2020-09-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200910_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
