# Generated by Django 3.0.5 on 2020-07-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25, unique=True)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
